In [126]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import math

#### Create Dataset

In [127]:
iris_dataset = load_iris()
iris_dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [128]:
iris_dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [129]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [130]:
print(iris_dataset.data.shape)
iris_dataset.target.shape

(150, 4)


(150,)

In [131]:
iris_dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [132]:
X = iris_dataset.data
y = (iris_dataset.target == 0).astype(np.int64)

In [133]:
dataset = np.column_stack((X, y))
np.random.shuffle(dataset)
dataset[:10]

array([[4.9, 3.1, 1.5, 0.2, 1. ],
       [5. , 3. , 1.6, 0.2, 1. ],
       [6.3, 2.3, 4.4, 1.3, 0. ],
       [6.4, 2.8, 5.6, 2.2, 0. ],
       [6.6, 3. , 4.4, 1.4, 0. ],
       [6.3, 3.3, 4.7, 1.6, 0. ],
       [4.9, 3.6, 1.4, 0.1, 1. ],
       [6. , 2.2, 5. , 1.5, 0. ],
       [7.9, 3.8, 6.4, 2. , 0. ],
       [5.1, 3.8, 1.5, 0.3, 1. ]])

In [134]:
train_test_split_ratio = math.floor(dataset.shape[0] * 0.95)
train_test_split_ratio

142

In [200]:
X_train, y_train = dataset[:train_test_split_ratio, :4], dataset[:train_test_split_ratio, -1].reshape(-1, 1)
X_test, y_test = dataset[train_test_split_ratio:, :4], np.array(dataset[train_test_split_ratio:, -1]).reshape(-1, 1)
print(y_train.shape)


(142, 1)


In [201]:
X_train[:5]

array([[4.9, 3.1, 1.5, 0.2],
       [5. , 3. , 1.6, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [6.6, 3. , 4.4, 1.4]])

In [202]:
y_train[:5]

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.]])

#### Perceptron with singular TLU

In [437]:
class Perceptron(object):
    def __init__(self, X, weights, y):
        print(f'feature shape => {X.shape}')
        print(f'targets shape => {y.shape}')
        self.X = X
        self.weights = weights
        self.y = y

    def heaviside(self, z):
        return np.where(z >= 0, 1, 0)
    
    def predict(self, X):
        z = self.weights.dot(X.T)
        return self.heaviside(z)

    def train_model(self, iterations=1000, eta=0.0001):
        print(f'Starting Training...\nWeights at first - {self.weights}')
        for i in range(iterations):

            prediction = self.predict(self.X).T
            error = self.y - prediction            
            self.weights += eta * np.dot(self.X.T, error).squeeze() 

            
            if ((i + 1) % 100 == 0):
                print(f'y - {self.y.shape} prediction - {prediction.shape} error - {error.shape} weights - {self.weights.shape}')
                print(f'Weights at Iteration {i + 1} - {self.weights}')

In [438]:
weights = np.random.rand(1, 4)
perceptron = Perceptron(X_train, weights, y_train)

feature shape => (142, 4)
targets shape => (142, 1)


In [439]:
perceptron.train_model()

Starting Training...
Weights at first - [[0.30488188 0.3021439  0.75947466 0.1075339 ]]
y - (142, 1) prediction - (142, 1) error - (142, 1) weights - (1, 4)
Weights at Iteration 100 - [[-0.14592812  0.2180239   0.08131466 -0.1557361 ]]
y - (142, 1) prediction - (142, 1) error - (142, 1) weights - (1, 4)
Weights at Iteration 200 - [[-0.13386812  0.2227239   0.06686466 -0.1618861 ]]
y - (142, 1) prediction - (142, 1) error - (142, 1) weights - (1, 4)
Weights at Iteration 300 - [[-0.12360812  0.2263839   0.05157466 -0.1683861 ]]
y - (142, 1) prediction - (142, 1) error - (142, 1) weights - (1, 4)
Weights at Iteration 400 - [[-0.11820812  0.2284639   0.04545466 -0.1710461 ]]
y - (142, 1) prediction - (142, 1) error - (142, 1) weights - (1, 4)
Weights at Iteration 500 - [[-0.11820812  0.2284639   0.04545466 -0.1710461 ]]
y - (142, 1) prediction - (142, 1) error - (142, 1) weights - (1, 4)
Weights at Iteration 600 - [[-0.11820812  0.2284639   0.04545466 -0.1710461 ]]
y - (142, 1) prediction 

In [436]:
print('Test Set Prediction:\n')
for i in range(X_test.shape[0]):
    print(f'Prediction - {perceptron.predict(X_test[i])} Actual - {y_test[i]}')

Test Set Prediction:

Prediction - [0] Actual - [0.]
Prediction - [0] Actual - [0.]
Prediction - [0] Actual - [0.]
Prediction - [0] Actual - [0.]
Prediction - [1] Actual - [1.]
Prediction - [0] Actual - [0.]
Prediction - [1] Actual - [1.]
Prediction - [1] Actual - [1.]
